### ISSUE TITLE
Failed to load dump

### ISSUE THREAD

**Issue by madushan1000** [ecos-wtf/programstore-loader#1]
I tried loading https://github.com/jclehner/bcm2-dumps/blob/master/fast3890/FAST3890_TLC_50.10.11.T1_sto.bin with the loader and it failed with an empty error message. 
I'm running on macos so I had to compile Programstore binary myself from the source and replace yours. Any idea how to debug this? Can you load the mentioned dump on your system?

**Comment by qkaiser** [comment]
Hi ! I don't have any issues on my machine with this specific file:

![image](https://user-images.githubusercontent.com/569494/120049291-cd89af00-c019-11eb-95f6-5523bf77f138.png)

The module expects your ProgramStore binary to be in a specific location, where did you save yours ?

**Comment by qkaiser** [comment]
Which version of Ghidra are you using ? On a Linux box with Ghidra 9.1.2, the compiled ProgramStore binary should be in `/home/username/ghidra_9.1.2/Ghidra/Extensions/ProgramStoreLoader/lib`

**Comment by madushan1000** [comment]
I was using ghidra 9.2 and then compiled the extension myself for 9.2.3.
But I realized that the problem might not be with the extension.
Programstore binary I compiled refuse to extract the .bin file and create
an empty file. For some dumps it fills the file with zeros.

**Comment by qkaiser** [comment]
I'm closing this given that the issue affects your setup and not the loader itself.

**Comment by madushan1000** [comment]
Oh, I forgot to mention that I had to modify programstore to remove the -m32 flag from the makefile because macos doesn't support 32bit binaries now. I guess programstore doesn't support running on 64bit arch. Thank you for you help :)
